name: 'Pull Request merge action'
description: 'This action will merge a certain PR in a certain repo'
author: 'Kostiantyn Kulbachnyi'
branding:
  icon: 'git-pull-request'  
  color: 'green'
inputs:
  token:
    required: true
    description: 'GitHub authentication token, can be PAT or Application JWT token'
  owner:
    required: true
    description: 'Repository owner/organization name'
  repo:
    required: true
    description: 'Repository name'
  pull_number:
    required: true
    description: 'Number of Pull  Request'
  merge_method:
    required: false
    description: 'Merge method to use. Possible values are merge, squash or rebase. Default is merge.'
    default: 'merge'
  commit_title:
    required: false
    description: 'Title for the automatic commit message.'
  commit_message:
    required: false
    description: 'Extra detail to append to automatic commit message.'
  test_mode: 
    required: false
    description: 'Only exists for the automated test to pass'
runs:
  using: 'node16'
  main: 'dist/index.js'
